
const COUNTRY = {
    LOAD: 'COUNTRY_LOAD',
    LOAD_SUCCESS: 'COUNTRY_LOAD_SUCCESS',
    LOAD_FAIL: 'COUNTRY_LOAD_FAIL',
}

const STATES = {
    LOAD: 'STATES_LOAD',
    LOAD_SUCCESS: 'STATES_LOAD_SUCCESS',
    LOAD_FAIL: 'STATES_LOAD_FAIL',
}

const CITY = {
    LOAD: 'CITY_LOAD',
    LOAD_SUCCESS: 'CITY_LOAD_SUCCESS',
    LOAD_FAIL: 'CITY_LOAD_FAIL',
}

export { COUNTRY, STATES, CITY }
